moves:
    list:
        Mambo on 2:
            - name: Broken left turn
              counts: 8
            - name: Chuck step
              counts: 8
            - name: Hook step
              counts: 8
            - name: Hook turn
              counts: 8
            - name: In and outs
              counts: 8
            - name: Invert 1/5
              counts: 8
            - name: Left turn
              counts: 8
            - name: Mambo taps
              counts: 8
            - name: Pachanga
              counts: 8
            - name: Pachanga walk
              counts: 16
            - name: Push step
              counts: 8
            - name: Reverse grapevine
              counts: 8
            - name: Reverse grapevine (Nelson)
              counts: 8
            - name: Right turn
              counts: 8
            - name: Side charge
              counts: 16
            - name: Side cross
              counts: 8
            - name: Son step contratiempo
              counts: 8
            - name: Spot turn
              counts: 8
            - name: Step touch
              counts: 8
            - name: Suzie Q
              counts: 8
            - name: Swing Step
              counts: 8
            - name: Two Corner Swing
              counts: 8
maxmoves: 5
minmoves: 2
text:
    size: 40
song:
    bpm: 90
    sleepforrand: 5
    sleepforconst: 5
