moves:
  list:
    - name: "Swing Step"
      counts: 8
    - name: "Two Corner Swing"
      counts: 8
    - name: "Suzie Q"
      counts: 8
    - name: "Invert 1/5"
      counts: 8
    - name: "Side charge"
      counts: 16
    - name: "Left turn"
      counts: 8
    - name: "Right turn"
      counts: 8
    - name: "Broken left turn"
      counts: 8
    - name: "Pachanga"
      counts: 8
  max: 5
  min: 2
text:
  size: 24
